$(function () {

    var liste = [

        "Abricot",
        "Acidulée",
        "Ail",
        "Amande amère",
        "Anis",
        "Aromatique",
        "Banane",
        "Baume du Pérou",
        "Bitume",
        "Bois",
        "Bois de cèdre",
        "Bonbon anglais",
        "Cadavérique",
        "Cage aux fauves",
        "Camphre",
        "Cannelle",
        "Caoutchouc",
        "Carotte",
        "Céleri",
        "Chair brûlée",
        "Chicorée",
        "Chiffon mouillé",
        "Chocolat",
        "Chou pourri",
        "Cigüe",
        "Cire",
        "Cire brûlée",
        "Citron",
        "Concombre",
        "Corne brûlée",
        "Coumarine",
        "Crottin de cheval",
        "Croûte de fromage",
        "Crustacés",
        "Cuir de Russie",
        "Curry",
        "DDT",
        "Désagréable",
        "Eau de Javel",
        "Echalotte",
        "Encaustique",
        "Encens",
        "Epicée",
        "Farine",
        "Feuille de lierre",
        "Feuille de tomate",
        "Fénugrec",
        "Fleur d'oranger",
        "Fromage fort",
        "Fruitée",
        "Fumée de locomotive",
        "Gaz d'éclairage",
        "Hareng",
        "Herbe",
        "Insecticide",
        "Iode",
        "Iris",
        "Liqueur de poire",
        "Maggi",
        "Mandarine",
        "Mastic",
        "Menthe",
        "Métal",
        "Miel",
        "Mirabelle",
        "Moisi",
        "Moutarde",
        "Naphtaline",
        "Nitreuse",
        "Noisette",
        "Noix de coco",
        "Pain d'épice",
        "Pastèque",
        "Pelargonium",
        "Persil",
        "Plumes mouillées",
        "Poire",
        "Poisson",
        "Poivre",
        "Polypore",
        "Pomme",
        "Prune",
        "Punaise",
        "Purée de pomme de terre refroidie",
        "Rance",
        "Rave",
        "Réglisse",
        "Résine",
        "Rhubarbe",
        "Riz sec",
        "Romarin",
        "Rose",
        "Rose fanée",
        "Sardine",
        "Savon",
        "Scléroderme",
        "Soufre",
        "Sperme",
        "Sucre brûlé",
        "Sueur de pieds",
        "Tabac",
        "Terre",
        "Topinambour",
        "Urine",
        "Urine de souris",
        "Viande",
        "Vinaigre"

    ];


    $('#smell').autocomplete({

        source: liste

    });
});



